name: Build To Do app
on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
        TOKEN: ${{ secrets.TOKEN }}
        KEY: ${{ secrets.KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker build --target test --tag my-test-image .    
    - name: Running tests
      run: docker run my-test-image test/test_viewmodel.py  &&  docker run  -e TOKEN -e KEY my-test-image test/test_selenium.py && docker run  -e TOKEN -e KEY my-test-image test/test_trello_mock.py


      
  push:
    name: Publish
    runs-on: ubuntu-latest
    
    needs:  build
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1  
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker build --target production --tag rajeshdewan/todoapp:production .
    - run: docker push rajeshdewan/todoapp:production

  
  
  deploy:
    name: DeploytoHeroku
    runs-on: ubuntu-latest
    
    #needs:  build
    steps:
    - uses: actions/checkout@v2
    - uses: uses: gonuit/heroku-docker-deploy@v1.3.3  
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "todoappfordevops"
          heroku_email: "rajeshd1306@gmail.com"

    - run: docker tag rajeshdewan/todoapp:production registry.heroku.com/todoappfordevops/web
    - run: docker push registry.heroku.com/todoappfordevops/web
