name: Build To Do app
on:
  push:
    paths-ignore:
    - '**/README.md'
  # pull_request:
  #   paths-ignore:
  #   - '**/README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
        TOKEN: ${{ secrets.TOKEN }}
        KEY: ${{ secrets.KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker build --target test --tag my-test-image .    
    - name: Running tests
      run: docker run my-test-image test/test_viewmodel.py  &&  docker run  -e TOKEN -e KEY my-test-image test/test_selenium.py && docker run  -e TOKEN -e KEY my-test-image test/test_trello_mock.py

    

  # push:
  #   name: Publish
  #   run:  echo "Publishing"
  #   needs:  Build and test
  #   steps:
  #   - name: Login to Docker Hub
  #   - uses: docker/login-action@v1
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - run: docker build --target production --tag todo-app:prod .
  #   - run: docker push production
